## 학습목표
- 배열과 리스트의 차이점
- 배열 생성 다루는 기법
- 기술 통계
- 결과에 대한 분석하는 방법

- 넌파이의 배열은 모든 원소가 같은 자료형이여야한다.(resizing이 안된다.)ㅋ

- Vextor(차원, 배열)을 pandas에서는 Series라고 한다.
- Matrix(차원, 행렬)을 pandas에서는 DataFrame이라고 한다.

- 선형대수(행렬을 이용한 연산이 가능하다.)

In [1]:
import numpy as np

- 배열의 차원과 크기, 타입
- ndim, shape, dtype

In [2]:
def aryInfo(ary):
    print('type : {}'.format(type(ary)))
    print('shape : {}'.format(ary.shape))
    print('dimension : {}'.format(ary.ndim))
    print('type : {}'.format(ary.dtype))
    print('Array Data : \n', ary)

# 1차원 배열 생성
- array()사용

In [4]:
oneAry = np.array([0,1,2,3,4,5,6,7,8,9])
aryInfo(oneAry)

type : <class 'numpy.ndarray'>
shape : (10,)
dimension : 1
type : int32
Array Data : 
 [0 1 2 3 4 5 6 7 8 9]


- List vs Array의 차이점(Vwctor operation)

In [5]:
data = [0,1,2,3,4,5,6,7,8,9]
data*2

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [6]:
result = []
for d in data:
    result.append(d*2)
result

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [10]:
result2 = [d * 2 for d in data]
result2

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [11]:
result3 = oneAry * 2
result3

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

- 백터 연산은 비교, 산술, 논리 연산을 포함하는 모든 수학연산에 적용된다.

In [15]:
xAry = np.array([1,2,3])
yAry = np.array([10,20,30])

In [18]:
print(xAry * yAry)
print(2 * xAry + yAry)

[10 40 90]
[12 24 36]


In [19]:
xAry == 2

array([False,  True, False])

In [20]:
yAry > 20

array([False, False,  True])

In [21]:
(xAry == 2) & (yAry > 20)

array([False, False, False])

## 2차원 배열 생성

- ndarray(N-dimensional Array)
- 2차원, 3차원(다차원 배열 자료구조
- 2차원 배열은 행렬(Matrix)
- list of list
- list of list of list

In [28]:
# 2개의 행과 3개의 열을 가지는 배열을 만드시오
twoAry = np.array([[1,2,3], [4,5,6]], dtype=np.float64)
# twoAry = np.array([[1,2,3], [4,5,'6']])
# twoAry = np.array([[1,2,3], [4,5,6]])
aryInfo(twoAry)

type : <class 'numpy.ndarray'>
shape : (2, 3)
dimension : 2
type : float64
Array Data : 
 [[1. 2. 3.]
 [4. 5. 6.]]


In [24]:
# 행의 개수 확인
print(len(twoAry))
# 열의 개수 확인
print(len(twoAry[0]))
print(len(twoAry[1]))

2
3
3


# 3차원 배열 생성

In [34]:
# 3 * 4행렬 2개 만들기
threeAry = np.array([ [[1,2,3,4],
                      [5,6,7,8],
                      [9,10,11,12]],
                      [[13,14,15],
                      [16,17,18],
                      [19,20,21,22]] ])
aryInfo(threeAry)

type : <class 'numpy.ndarray'>
shape : (2, 3)
dimension : 2
type : object
Array Data : 
 [[list([1, 2, 3, 4]) list([5, 6, 7, 8]) list([9, 10, 11, 12])]
 [list([13, 14, 15]) list([16, 17, 18]) list([19, 20, 21, 22])]]


In [37]:
print('dept', len(threeAry))
print('row', len(threeAry[0]))
print('row', len(threeAry[1]))
print('row[0] col', len(threeAry[0][0]))

dept 2
row 3
row 3
row[0] col 4


- 요소의 타입을 변경할 때는 astype()

In [38]:
typeChange = threeAry.astype(np.float64)
aryInfo(typeChange)

ValueError: setting an array element with a sequence.

In [39]:
indexAry[2]

NameError: name 'indexAry' is not defined

In [ ]:
indexAry[-1]

In [44]:
# twoAry indexing
# 첫 번째 행의 첫 번째 열
print(twoAry[0][0])
# 첫 번째 행의 두 번째 열
print(twoAry[0][1])
# 마지막 행의 마지막 열
print(twoAry[-1][-1])

1.0
2.0
6.0


In [51]:
slicingAry = np.array([[1,2,3,4],[5,6,7,8]])
aryInfo(slicingAry)
# 첫 번재 행의 전체 출력
print(slicingAry[0, : ])
# 두 번째 열의 전체 출력
print(slicingAry[ : , 1])
# 두 번째 행의 두 번째 열부터 끝까지 출력
print(slicingAry[1, 1: ])

type : <class 'numpy.ndarray'>
shape : (2, 4)
dimension : 2
type : int32
Array Data : 
 [[1 2 3 4]
 [5 6 7 8]]
[1 2 3 4]
[2 6]
[6 7 8]


In [67]:
m = np.array([[ 0,  1,  2,  3,  4],
            [ 5,  6, 7,  8,  9],
            [10, 11, 12, 13, 14]])
aryInfo(m)

type : <class 'numpy.ndarray'>
shape : (3, 5)
dimension : 2
type : int32
Array Data : 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [68]:
# 이 행렬에서 값 7을 인덱싱 한다.
print(m[1, 2])
# 이 행렬에서 값 14를 인덱싱 한다.
print(m[-1, -1])
# 이 행렬에서 배열 [6,7]을 슬라이싱 한다.
print(m[1, 1:3])
# 이 행렬에서 배열[7,12]를 슬라이싱 한다.
print(m[1:, 2])
# 이 행렬에서 배열 [[3,4], [8,9]]를 슬라이싱 한다.
print(m[0:2, 3:5])

7
14
[6 7]
[ 7 12]
[[3 4]
 [8 9]]


- fancy indexing
- boolen indexing

In [76]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
aryInfo(arr)
idx = np.array([True, False, True, False, True, False, True, False, True, False, True, False])
print(arr[arr])

type : <class 'numpy.ndarray'>
shape : (10,)
dimension : 1
type : int32
Array Data : 
 [0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]


In [70]:
arr % 2 == 0

array([ True, False,  True, False,  True, False,  True, False,  True,
       False])

In [73]:
arr[arr % 2 == 0]

array([0, 2, 4, 6, 8])

In [75]:
cntIdx = np.array([0,2,4,6,8])
print(arr[cntIdx])

[0 2 4 6 8]


In [89]:
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
             11, 12, 13, 14, 15, 16, 17, 18, 19, 20])
aryInfo(x)
# 이 배열에서 3의 배수를 찾아라.
print(x[x % 3 == 0])
# 이 배열에서 4로 나누면 1이 남는 수를 찾아라.
print(x[x % 4 == 1])
# 이 배열에서 3으로 나누면 나누어지고 4로 나누면 1이 남는 수를 찾아라.
print(x[(x % 3 == 0) & (x % 4 == 1)])

type : <class 'numpy.ndarray'>
shape : (20,)
dimension : 1
type : int32
Array Data : 
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[ 3  6  9 12 15 18]
[ 1  5  9 13 17]
[9]


In [91]:
# 배열의 index 배열을 전달하여 배열 요소를 참조하시오.
fancyAry = np.arange(0, 12, 1).reshape(3,4)
aryInfo(fancyAry)

type : <class 'numpy.ndarray'>
shape : (3, 4)
dimension : 2
type : int32
Array Data : 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [103]:
# 값 10을 가져오시오.
print(fancyAry[2,2])
# 값 6을 가져오시오.
print(fancyAry[1,2])
print(fancyAry[1:2,2])
# 값 2와 10을 가져오시오.
print(fancyAry[0,2], fancyAry[2,2])
print(fancyAry[[0,2], 2])
aryInfo(fancyAry[[0,2], 2])
# 값 2와 10을 가져오고 2차원으로 만드시오
aryInfo(fancyAry[[0,2], 2].reshape(1,2))
aryInfo(fancyAry[[0,2], 2:3])

10
6
[6]
2 10
[ 2 10]
type : <class 'numpy.ndarray'>
shape : (2,)
dimension : 1
type : int32
Array Data : 
 [ 2 10]
type : <class 'numpy.ndarray'>
shape : (1, 2)
dimension : 2
type : int32
Array Data : 
 [[ 2 10]]
type : <class 'numpy.ndarray'>
shape : (2, 1)
dimension : 2
type : int32
Array Data : 
 [[ 2]
 [10]]


In [104]:
aryInfo(fancyAry[ [0,2], [0,2] ])

type : <class 'numpy.ndarray'>
shape : (2,)
dimension : 1
type : int32
Array Data : 
 [ 0 10]


In [109]:
rowIdx = np.array([0,2])
colIdx = np.array([0,2])
print(fancyAry[[rowIdx]] [ : ,colIdx])

[[ 0  2]
 [ 8 10]]


<ipython-input-109-5c2e6e8e15f9>:3: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  print(fancyAry[[rowIdx]] [ : ,colIdx])


# 배열 변형(타입, 형태)

In [114]:
# x = np.array([1,2,3], dtype='f') # 실수 형태
x = np.array([1,2,3], dtype='U') # 유니코드 형태
aryInfo(x)

type : <class 'numpy.ndarray'>
shape : (3,)
dimension : 1
type : <U1
Array Data : 
 ['1' '2' '3']


In [113]:
x[0] + x[1]

3.0

- Inf(무한) vs NaN(값없음)

In [115]:
np.array([0,1,-1,0]/np.array([1,0,0,1]))

<ipython-input-115-9d227ea4c64f>:1: RuntimeWarning: divide by zero encountered in true_divide
  np.array([0,1,-1,0]/np.array([1,0,0,1]))


array([  0.,  inf, -inf,   0.])

In [116]:
np.log(0)

<ipython-input-116-f6e7c0610b57>:1: RuntimeWarning: divide by zero encountered in log
  np.log(0)


-inf

- zeros, ones
- zeros_like, ones_like
- empty
- arange
- linspace, logspace

In [121]:
# zeros : 키기가 정해져 있고 모든 값이 0인 배열을 생성시에 사용
# z = np.zeros(5)
z = np.zeros(5, dtype='U')
aryInfo(z)

type : <class 'numpy.ndarray'>
shape : (5,)
dimension : 1
type : <U1
Array Data : 
 ['' '' '' '' '']


In [120]:
z = np.zeros((2,3), dtype='i')
aryInfo(z)

type : <class 'numpy.ndarray'>
shape : (2, 3)
dimension : 2
type : int32
Array Data : 
 [[0 0 0]
 [0 0 0]]


In [125]:
# o = np.ones((2,3,4), dtype='i') # type : int32
o = np.ones((2,3,4), dtype='i8') # type : int64
aryInfo(o)

type : <class 'numpy.ndarray'>
shape : (2, 3, 4)
dimension : 3
type : int64
Array Data : 
 [[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]


In [126]:
o_like = np.ones_like(o, dtype='f')
aryInfo(o_like)

type : <class 'numpy.ndarray'>
shape : (2, 3, 4)
dimension : 3
type : float32
Array Data : 
 [[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [127]:
z_like = np.zeros_like(z)
aryInfo(z_like)

type : <class 'numpy.ndarray'>
shape : (5,)
dimension : 1
type : <U1
Array Data : 
 ['' '' '' '' '']


In [128]:
e = np.empty((4,3))
aryInfo(e)

type : <class 'numpy.ndarray'>
shape : (4, 3)
dimension : 2
type : float64
Array Data : 
 [[0.0078125 0.0078125 0.0078125]
 [0.0078125 0.0078125 0.0078125]
 [0.0078125 0.0078125 0.0078125]
 [0.0078125 0.0078125 0.0078125]]


In [129]:
a = np.arange(10)
aryInfo(a)

type : <class 'numpy.ndarray'>
shape : (10,)
dimension : 1
type : int32
Array Data : 
 [0 1 2 3 4 5 6 7 8 9]


In [130]:
a = np.arange(3, 21, 2)
aryInfo(a)

type : <class 'numpy.ndarray'>
shape : (9,)
dimension : 1
type : int32
Array Data : 
 [ 3  5  7  9 11 13 15 17 19]


- 전치행렬(transpose matrix, T) : 행은 열로, 열은 행으로 바꿔도 바꾸기 전과 값이 같은 행렬
- transpose opertion

In [132]:
arr = np.array([[1,2,3], [4,5,6]])
aryInfo(arr)

type : <class 'numpy.ndarray'>
shape : (2, 3)
dimension : 2
type : int32
Array Data : 
 [[1 2 3]
 [4 5 6]]


In [133]:
arr_transpose = arr.T
aryInfo(arr_transpose)

type : <class 'numpy.ndarray'>
shape : (3, 2)
dimension : 2
type : int32
Array Data : 
 [[1 4]
 [2 5]
 [3 6]]


In [134]:
# Vector에 transpose 가능여부 확인 -> 가능하지만 의미가 없다
vec = np.arange(10)
aryInfo(vec)

type : <class 'numpy.ndarray'>
shape : (10,)
dimension : 1
type : int32
Array Data : 
 [0 1 2 3 4 5 6 7 8 9]


In [135]:
vec_transpose = vec.T
aryInfo(vec_transpose)

type : <class 'numpy.ndarray'>
shape : (10,)
dimension : 1
type : int32
Array Data : 
 [0 1 2 3 4 5 6 7 8 9]


In [139]:
# vec_transpose = vec.reshape(1,10)
vec_transpose = vec.reshape(1,10).T
aryInfo(vec_transpose.T)

type : <class 'numpy.ndarray'>
shape : (1, 10)
dimension : 2
type : int32
Array Data : 
 [[0 1 2 3 4 5 6 7 8 9]]


- 배열의 원소를 순차적으로 access 하고자 한다면?
- for(Vector, Matrix)
- imterator(inteernext(), finished 속성을 이용해서 ndarray 모든 요소를 순차적으로 접근 할 수 있다.

In [152]:
arr = np.array([1,2,3,4,5])

In [146]:
for tmp in arr :
    print(tmp, end=" ")

1 2 3 4 5 

In [147]:
for idx in range(len(arr)):
    print(arr[idx], end=" ")

1 2 3 4 5 

In [157]:
ite = np.nditer(arr, flags=["c_index"])
while not ite.finished:
    print(arr[ite.index], end=" ")
    ite.iternext()

1 2 3 4 5 

In [158]:
arr = np.array([[1,2,3], [4,5,6]])
aryInfo(arr)

type : <class 'numpy.ndarray'>
shape : (2, 3)
dimension : 2
type : int32
Array Data : 
 [[1 2 3]
 [4 5 6]]


In [172]:
for i in range(arr.shape[0]):
    for j in range(arr.shape[1]):
        print(arr[i, j], end="\t")
    print("\n")

1	2	3	

4	5	6	



In [173]:
ite = np.nditer(arr, flags=["multi_index"])
while not ite.finished:
    print(arr[ite.multi_index], end=" ")
    ite.iternext()

1 2 3 4 5 6 